[user]
enable_graphics = true
enable_random_maze = true
menu_enable = true
sound_enable = false

[graphics]
width = 720
height = 720
fps = 60
title = "PacMan"
maze_path = "assets/data/maze.txt"

[game]
game_speed = 1.5
pacman_lives = 3
super_mode_duration = 10
scatter_duration = 6
chase_duration = 5

[maze]
width = 21
height = 21
density = 0.8
seed = 1
intersection_step = 3
is_symetric = false
random_maze_path = "assets/data/random.txt"

[genetic]
genetic_enable = false
move_path = "assets/data/moves.txt"
population_size = 20
graded_retain_percentage = 0.40
mutation_chance = 0.25
deletion_chance = 0.05
addition_chance = 0.80
replacement_chance = 0.15
selection_type = "rank"

[dqn]
dqn_enable = true
output_dir = "assets/model_output/pacman"
weights_path = "weights_0100.hdf5"
state_size = 230
action_size = 4
batch_size = 64
episodes = 100001
learning_rate = 0.001

[policy]
policy_enable = false

[aplus]
aplus_enable = false