[user]
enable_graphics = true
enable_random_maze = true
menu_enable = false
sound_enable = false

[graphics]
width = 720
height = 720
fps = 120
title = "PacMan"
maze_path = "assets/data/maze.txt"

[game]
game_speed = 1.5
pacman_lives = 1
super_mode_duration = 10
scatter_duration = 6
chase_duration = 20

[maze]
width = 15
height = 15
density = 0.85
seed = -1
intersection_step = 3
is_symetric = false
random_maze_path = "assets/data/random.txt"

[genetic]
genetic_enable = false
move_path = "assets/data/moves.txt"
population_size = 100
graded_retain_percentage = 0.40
mutation_chance = 0.25
deletion_chance = 0.05
addition_chance = 0.80
replacement_chance = 0.15
selection_type = "rank"

[dqn]
dqn_enable = true
output_dir = "assets/model_output/pacman"
weights_path = "weights_21500.hdf5"
state_size = 230
action_size = 4
batch_size = 128
episodes = 100001
learning_rate = 0.00035

[policy]
policy_enable = false