[user]
enable_graphics = true
enable_random_maze = false
menu_enable = false
sound_enable = true

[graphics]
width = 720
height = 720
fps = 120
title = "PacMan"
maze_path = "assets/data/maze.txt"

[game]
game_speed = 1.2
pacman_lives = 1
super_mode_duration = 10
scatter_duration = 6
chase_duration = 20

[maze]
width = 15
height = 15
density = 0.8
seed = 1
intersection_step = 3
is_symetric = false
random_maze_path = "assets/data/random.txt"

[genetic]
genetic_enable = false
move_path = "assets/data/moves.txt"
population_size = 20
graded_retain_percentage = 0.40
mutation_chance = 0.25
deletion_chance = 0.05
addition_chance = 0.80
replacement_chance = 0.15
selection_type = "rank"
population_type = "clone_pop"
max_generation = -1